---

- name: Check for existing installations
  find:
    path: "/opt/rh/"
    file_type: directory
    patterns: "rh-php*"
  register: old_versions

- name: Ensure all SCLPHP versions are stopped and disabled
  service:
    name: "{{ item.path | basename }}-php-fpm"
    state: stopped
    enabled: false
  with_items:
    - "{{ old_versions.files }}"

- name: Enable and start defined PHP FPM service
  service:
    name: "{{sclphp_version}}-php-fpm"
    state: started
    enabled: yes
    force: yes

- name: Set PHP timezone
  replace:
    dest: "/etc/opt/rh/{{sclphp_version}}/php.ini"
    regexp: >
      ^;date.timezone =$
    replace: "date.timezone = America/Chicago"

- name: Enable SCL PHP 5.6 for interactive users
  template:
    src: enablephp.sh.j2
    dest: /etc/profile.d/enablephp.sh
    mode: 0755
    owner: root
    group: wheel
  when: sclphp_global

# - name: Disable display of errors in browser
#   replace:
#     dest: /etc/opt/rh/{{sclphp_version}}/php.ini
#     regexp: >
#       ^;display_errors = On$
#     replace: "display_errors = Off"


- name: Configure nginx-oriented php-fpm
  template:
    src: "www.conf.j2"
    dest: "/etc/opt/rh/{{sclphp_version}}/php-fpm.d/www.conf"
    owner: nginx
    group: wheel

- name: Add symlink to make php logs more findable
  file:
    src: "/var/opt/rh/{{sclphp_version}}/log/php-fpm"
    dest: "/var/log/php-fpm"
    state: link
    owner: nginx
    group: wheel

- name: Set group on php-fpm logs to allow wheel access
  file:
    path: "/var/opt/rh/{{sclphp_version}}/log/php-fpm"
    state: directory
    owner: nginx
    group: wheel
