---
- name: Install scl repo
  yum:
    name:
      - centos-release-scl
    state: present

- name: Install PHP from scl
  yum:
    name:
      - "{{sclphp_version}}"
      - "{{sclphp_version}}-php-fpm"
      - "{{sclphp_version}}-php-mysqlnd"
      - "{{sclphp_version}}-php-gd"
      - "{{sclphp_version}}-php-mbstring"
    state: present
